# Generated by Django 5.2.8 on 2025-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='draft_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='draft_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='draft_message_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
